accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.loginUser, name='loginUser'),
    path('register/', views.register, name='register'),
    path('logout/', views.logoutUser, name='logoutUser'),
    path('reset_password/', views.resetPassword, name='resetPassword'),
    path('reset_password_sent/', views.resetPasswordSent,
         name='resetPasswordSent'),
    path('reset', views.resetPasswordConfirm,
         name='resetPasswordConfirm'),
    path('reset_password_complete/', views.resetPasswordComplete,
         name='resetPasswordComplete'),
    path('invalid/', views.resetPasswordInvalid, name='resetPasswordInvalid'),
    path('expired/', views.resetPasswordExpired, name='resetPasswordExpired')
]

balancecontrol/urls.py
from django.urls import path

from . import views

app_name = 'balancecontrol'
urlpatterns = [
    path('', views.home, name='home'),
    path('createfinance/', views.createfinance, name='createfinance'),
    path('editfinance/', views.editfinance, name='editfinance'),
    path('deletefinance/', views.deletefinance, name='deletefinance'),
]

settings/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('balancecontrol.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

# Create your models here.


class PassawordResetToken(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=64, unique=True)
    datecreate = models.DateTimeField(default=timezone.now)
    expires_at = models.DateTimeField()

    def __str__(self):
        return self.token

    class Meta:
        verbose_name = 'Passaword Reset Token'
        verbose_name_plural = 'Passawords Reset Tokens'

accounts/views.py
import os
from datetime import timedelta

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.mail import BadHeaderError, send_mail
from django.core.validators import validate_email
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.utils import timezone
from django.utils.crypto import get_random_string

from .models import PassawordResetToken


# Create your views here.
def loginUser(request):
    template_name = 'accounts/pages/login.html'
    if request.method == 'GET':
        return render(request, template_name)

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('balancecontrol:home')
        else:
            messages.info(request, 'Username OR password is incorrect')
    return render(request, template_name)


def register(request):
    template_name = 'accounts/pages/register.html'

    if request.method != 'POST':
        return render(request, template_name)

    fistname = request.POST.get('firstname')
    lastname = request.POST.get('lastname')
    username = request.POST.get('username')
    email = request.POST.get('email')
    password = request.POST.get('password')
    password2 = request.POST.get('password2')

    if fistname == '' or lastname == '' or username == '' or email == '' \
            or password == '' or password2 == '':
        messages.info(request, 'Please fill all the fields')
        return render(request, template_name)
    try:
        validate_email(email)
    except:  # noqa
        messages.error(request, 'E-mail invalid!')
        return render(request, template_name)

    if len(password) < 6:
        messages.error(
            request, 'Password must be greater than 6 characters!')
        return render(request, template_name)
    if password == password2:
        if User.objects.filter(username=username).exists():
            messages.info(request, 'Username Taken')
            return render(request, template_name)
        elif User.objects.filter(email=email).exists():
            messages.info(request, 'Email Taken')
            return render(request, template_name)
        else:
            user = User.objects.create_user(
                first_name=fistname, last_name=lastname, username=username,
                email=email, password=password)
            user.save()
            messages.success(request, 'user created successfully')
            return redirect('accounts:loginUser')
    else:
        messages.info(request, 'Passwords not matching...')
        return render(request, template_name)


@login_required(login_url='accounts:loginUser', redirect_field_name='next')
def logoutUser(request):
    if request.method == 'POST':
        logout(request)
    return redirect('accounts:loginUser')


def resetPassword(request):
    template_name = 'accounts/pages/resetpassword.html'
    if request.method == 'POST':
        email = request.POST.get('email')
        if email == '':
            messages.info(request, 'Please fill the field')
        if User.objects.filter(email=email).exists():
            user = User.objects.get(email=email)
            if PassawordResetToken.objects.filter(user=user).exists():
                PassawordResetToken.objects.get(user=user).delete()
            token = get_random_string(length=64)
            resert_token = PassawordResetToken.objects.create(
                user=user,
                token=token,
                expires_at=timezone.now() + timedelta(hours=2)
            )

            subject = 'Password reset request'
            email_template_name = 'accounts/pages/password_message.txt'
            parametrs = {
                'email': user.email,
                'domain': os.environ.get('DOMAIN_NAME'),
                'site_name': 'Balance Control',
                'user': user,
                'token': resert_token,
                'protocol': 'http',
            }
            email = render_to_string(email_template_name, parametrs)
            try:
                send_mail(subject, email, '', [
                          user.email], fail_silently=False)
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            messages.success(request, 'Email sent successfully')
            return redirect('accounts:resetPasswordSent')
        else:
            messages.info(request, 'Email not found')
            return render(request, template_name)
    else:
        return render(request, template_name)


def resetPasswordSent(request):
    template_name = 'accounts/pages/resetpasswordsent.html'
    if request.method == 'GET':
        return render(request, template_name)


def resetPasswordConfirm(request):
    template_name = 'accounts/pages/resetpasswordconfirm.html'
    token = request.GET.get('token')
    try:
        resert_token = PassawordResetToken.objects.get(token=token)
    except PassawordResetToken.DoesNotExist:
        return render(request, 'accounts/pages/tokeninvalid.html')

    if resert_token.expires_at < timezone.now():
        return render(request, 'accounts/pages/tokenexpired.html')

    if request.method == 'POST':
        password = request.POST.get('password')
        password2 = request.POST.get('password2')
        if password == '' or password2 == '':
            messages.info(request, 'Please fill all the fields')
            return render(request, template_name)
        if len(password) < 6:
            messages.error(
                request, 'Password must be greater than 6 characters!')
            return render(request, template_name)
        if password == password2:
            user = resert_token.user
            user.set_password(password)
            user.save()
            resert_token.delete()
            messages.success(request, 'Password reset successfully')
            return redirect('accounts:resetPasswordComplete')
        else:
            messages.info(request, 'Passwords not matching...')
            return render(request, template_name)
    else:
        return render(request, template_name)


def resetPasswordInvalid(request):
    template_name = 'accounts/pages/resetpasswordinvalid.html'
    if request.method == 'GET':
        return render(request, template_name)


def resetPasswordExpired(request):
    template_name = 'accounts/pages/resetpasswordexpired.html'
    if request.method == 'GET':
        return render(request, template_name)


def resetPasswordComplete(request):
    template_name = 'accounts/pages/resetpasswordcomplete.html'
    if request.method == 'GET':
        return render(request, template_name)

accounts/templates/accounts/pages/login.html
{% extends 'base.html' %}
{% block title %}
Sign-in 
{% endblock title %}  
{% block navbar %}{% endblock navbar %}  
{% block content %}
<style>
    body {
        background: #007bff;
        background: linear-gradient(to right, #0062E6, #33AEFF);
    }

    .btn-login {
        font-size: 0.9rem;
        letter-spacing: 0.05rem;
        padding: 0.75rem 1rem;
    }
</style>

<body>
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                <div class="card border-0 shadow rounded-3 my-5">
                    <div class="card-body p-4 p-sm-5">
                        <h5 class="card-title text-center mb-5 fw-light fs-5">Sign In</h5>
                        {% include 'partial/_messages.html' %}
                        {% if request.user.is_authenticated %}
                            <div class="row text-center">
                                <h1>You are logged in.</h1>
                                <div class="d-grid">
                                    <div class="d-grid gap-2">
                                        <a href= {% url 'balancecontrol:home' %} 
                                        class="btn btn-outline-secondary" 
                                        type="button">
                                        <i class="bi bi-house"></i> Home
                                        </a>
                                    </div>
                            </div>    
                        {%else%}
                        <form  action="{% url 'accounts:loginUser' %}"  method="POST">
                            {% csrf_token %}
                            <div class="form-floating mb-3">
                                <input type="text" class="form-control" id="floatingInput" name="username" placeholder="User" required>
                                <label for="floatingInput">User</label>
                            </div>
                            <div class="form-floating">
                                <input type="password" class="form-control" id="floatingPassword" name="password" placeholder="Password" required>
                                <label for="floatingPassword">Password</label>
                            </div>
                            <br>
                            <div class="d-grid">
                                <button class="btn btn-primary btn-login text-uppercase fw-bold mb-3" type="submit">Sign
                                    in</button>
                            </div>
                        </form>
                            <div class="d-grid">
                                <a href="{% url 'accounts:resetPassword' %}" class="btn btn-light btn-login text-uppercase fw-bold">Recover Password</a>
                            </div>
                            <hr class="my-4">
                            <div class="d-grid gap-2">
                                <a href= {% url 'accounts:register' %} 
                                class="btn btn-outline-secondary" 
                                type="button">
                                <i class="bi bi-person-plus"></i> Register
                                </a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock content %}
{% block footer %}
{% endblock footer %}

accounts/templates/accounts/pages/register.html
{% extends 'base.html' %}

{% block title %}
Register
{% endblock title %}
{% block navbar %}{% endblock navbar %}  

{% block content %}
<section style="background-color: #eee;">
    <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-12 col-xl-11">
                <div class="card text-black" style="border-radius: 25px;">
                    <div class="card-body p-md-5">
                        <div class="row justify-content-center">
                            {% if request.user.is_authenticated %}
                            <div class="row text-center">
                                <h1>You are logged in.</h1>
                                <div class="d-grid">
                                    <div class="d-grid gap-2">
                                        <a href= {% url 'balancecontrol:home' %} 
                                        class="btn btn-outline-secondary" 
                                        type="button">
                                        <i class="bi bi-house"></i> Home
                                        </a>
                                    </div>
                            </div>   
                            {%else%}
                            <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
                                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>
                                <form {% url 'accounts:register' %}  method="POST" class="mx-1 mx-md-4" autocompplete="off">
                                    {% csrf_token %}

                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="floatingInput" name="firstname" value="{{request.POST.firstname}}" placeholder="Fist Name">
                                        <label for="floatingInput">Fist Name</label>
                                    </div>                                        
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="floatingInput" name="lastname" value="{{request.POST.lastname}}" placeholder="Last Name">
                                        <label for="floatingInput">Last Name</label>
                                    </div>                                        
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="floatingInput" name="username" value="{{request.POST.username}}" placeholder="User Name">
                                        <label for="floatingInput">User Name</label>
                                    </div>                                    
                                    <div class="form-floating mb-3">
                                        <input type="email" class="form-control" id="floatingInput" name="email" value="{{request.POST.email}}" placeholder="name@example.com">
                                        <label for="floatingInput">Email address</label>
                                    </div>

                                    <div class="form-floating mb-3">
                                        <input type="password" class="form-control" id="floatingPassword" name="password" placeholder="Password">
                                        <label for="floatingPassword">Password</label>
                                    </div>
                                    <div class="form-floating mb-3">
                                        <input type="password" class="form-control" id="floatingPassword" name="password2" placeholder="Password">
                                        <label for="floatingPassword">Repet Passaword</label>
                                    </div>
                                    <br>                            
                                    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                        <button type="submit" class="btn btn-primary btn-lg">Register</button>
                                    </div>
                                </form>
                                <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                    <a href={% url 'accounts:loginUser' %}>
                                        <button type="submit" class="btn btn-outline-secondary btn-lg">Login</button>
                                    </a>
                                </div>
                           </div>
                            <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
                                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                                    class="img-fluid" alt="Sample image">
                            </div>
                            {%endif%}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}
{% block footer %}
{% endblock footer %}

accounts/templates/accounts/pages/resetpassword.html
{% extends 'base.html' %}
{% block title %}Password Reset Page{% endblock %}
{% block navbar %}{% endblock navbar %}  
{% block content %}
<div class="container">
    <div class="row mt-5 pt-3">
        <div class="col-md-8 offset-md-2">
            <div class="card my-3 shadow">
                <div class="card-body">
                    <h4>Password Reset Page</h4>
                    <hr>
                    <div class="alert alert-info">
                        Enter email and a mail will be sent with instructions to reset password
                    </div>
                    <form action="{% url 'accounts:resetPassword' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-floating mb-3">
                            <input type="email" class="form-control" id="floatingInput" name="email" placeholder="name@example.com">
                            <label for="floatingInput">Email address</label>
                          </div>
                        <input class="btn btn-primary btn-block" type="submit" value="Reset Password">
                    </form>
                    <hr>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block footer %}
{% endblock footer %}

accounts/templates/accounts/pages/resetpasswordcomplete.html
{% extends 'base.html' %}
{% block title %}Password Reset Complete Page{% endblock %}
{% block navbar %}{% endblock navbar %}  
{% block content %}
<div class="container">
    <div class="row mt-5 pt-3">
        <div class="col-md-8 offset-md-2">
            <div class="card my-3 shadow">
                <div class="card-body">
                    <h4>Password Reset Complete Page</h4>
                    <hr>
                    <div class="alert alert-info">
                        Your password reset is successful. Log in with new credentials
                    </div>
                    <div class="d-grid">
                        <a href="{% url 'accounts:loginUser' %}" class="btn btn-primary text-uppercase fw-bold">Login</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block footer %}
{% endblock footer %}

accounts/templates/accounts/pages/resetpasswordconfirm.html
{% extends 'base.html' %}
{% block title %}Password Reset Confirm Page{% endblock %}
{% block navbar %}{% endblock navbar %}  
{% block content %}
<div class="container">
    <div class="row mt-5 pt-3">
        <div class="col-md-8 offset-md-2">
            <div class="card my-3 shadow">
                <div class="card-body">
                    <h4>Password Reset Confirm Page</h4>
                    <hr>
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-floating mb-3">
                            <input type="password" class="form-control" id="floatingInput" name="password" placeholder="Password">
                            <label for="floatingInput">Password</label>
                        </div>                        
                        <div class="form-floating mb-3">
                            <input type="password" class="form-control" id="floatingInput" name="password2" placeholder="Repet Password">
                            <label for="floatingInput">Repet Password</label>
                        </div>
                        <input class="btn btn-primary btn-block" type="submit" value="Reset Password Confirm">
                    </form>
                    <hr>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block footer %}
{% endblock footer %}

accounts/templates/accounts/pages/resetpasswordsent.html
{% extends 'base.html' %}
{% block title %}Password Reset Done Page{% endblock %}
{% block navbar %}{% endblock navbar %}  
{% block content %}
<div class="container">
    <div class="row mt-5 pt-3">
        <div class="col-md-8 offset-md-2">
            <div class="card my-3 shadow">
                <div class="card-body">
                    <h4>Password Reset Done Page</h4>
                    <hr>
                    <div class="alert alert-info">
                        An mail with instructions to reset password has been sent to the email you provided.
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block footer %}
{% endblock footer %}

accounts/templates/accounts/pages/tokenexpired.html
{% extends 'base.html' %}
{% block title %}Expired Token{% endblock %}
{% block navbar %}{% endblock navbar %}  
{% block content %}
<div class="container">
    <div class="row mt-5 pt-3">
        <div class="col-md-8 offset-md-2">
            <div class="card my-3 shadow">
                <div class="card-body">
                    <h4>Expired Token!</h4>
                    <hr>
                    <div class="alert alert-info">
                        <h1>The useful time of this token has expired, ask again to reset your password.</h1>
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block footer %}
{% endblock footer %}

accounts/templates/accounts/pages/tokeninvalid.html
{% extends 'base.html' %}
{% block title %}Invalid Token{% endblock %}
{% block navbar %}{% endblock navbar %}  
{% block content %}
<div class="container">
    <div class="row mt-5 pt-3">
        <div class="col-md-8 offset-md-2">
            <div class="card my-3 shadow">
                <div class="card-body">
                    <h4>Invalid Token!</h4>
                    <hr>
                    <div class="alert alert-info">
                        <h1>This token is not valid, please access the right link or ask again to reset the password.</h1>
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block footer %}
{% endblock footer %}