accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.loginUser, name='loginUser'),
    path('register/', views.register, name='register'),
    path('logout/', views.logoutUser, name='logoutUser'),
    path('reset_password/', views.resetPassword, name='resetPassword'),
    path('reset_password_sent/', views.resetPasswordSent,
         name='resetPasswordSent'),
    path('reset', views.resetPasswordConfirm,
         name='resetPasswordConfirm'),
    path('reset_password_complete/', views.resetPasswordComplete,
         name='resetPasswordComplete'),
    path('invalid/', views.resetPasswordInvalid, name='resetPasswordInvalid'),
    path('expired/', views.resetPasswordExpired, name='resetPasswordExpired')
]

balancecontrol/urls.py
from django.urls import path

from . import views

app_name = 'balancecontrol'
urlpatterns = [
    path('', views.home, name='home'),
    path('createfinance/', views.createfinance, name='createfinance'),
    path('editfinance/', views.editfinance, name='editfinance'),
    path('deletefinance/', views.deletefinance, name='deletefinance'),
]

settings/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('balancecontrol.urls')),
    path('accounts/', include('accounts.urls')),
]

balancecontrol/models.py
from datetime import datetime
from secrets import token_hex

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


# Create your models here.
class Balance(models.Model):
    OPTION = (
        ("P", "Prohibited"),
        ("E", "Exit")
    )
    value = models.DecimalField(max_digits=19, decimal_places=2)
    typeoperation = models.CharField(max_length=1, choices=OPTION)
    datecreate = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    code = models.CharField(max_length=32, blank=True, null=True)

    def __str__(self):
        return f'{self.value:.2f}'.replace('.', ',')

    class Meta:
        verbose_name = 'Balance'
        verbose_name_plural = 'Balances'
        ordering = ['-datecreate']

    def save(self, *args, **kwargs):
        if not self.code:
            self.code = datetime.now().strftime('%S') + token_hex(4)
        super(Balance, self).save(*args, **kwargs)

balancecontrol/views.py
import os
from datetime import timedelta

from dateutil.parser import parse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils import timezone

from utils.pagination import make_pagination

from .models import Balance

PER_PAGE = int(os.environ.get('PER_PAGE', 6))

# Create your views here.


@login_required(login_url='accounts:loginUser', redirect_field_name='next')
def home(request):
    template_name = 'balancecontrol/pages/home.html'
    datebalances = Balance.objects.filter(
        user=request.user).order_by('-datecreate')

    # Search by date
    start_date = request.GET.get('start_date')
    end_date = request.GET.get('end_date')
    if start_date and end_date:
        end_date = parse(end_date) + timedelta(days=1)
        datebalances = datebalances.filter(
            datecreate__range=[start_date, end_date]
        )

    page_obj, pagination_range = make_pagination(
        request, datebalances, PER_PAGE)

    # calculate the daily total
    DailyAmountEntry = Balance.objects.all().filter(
        typeoperation='P', datecreate__day=timezone.now().day).aggregate(Sum('value'))  # noqa
    if DailyAmountEntry['value__sum'] is None:
        DailyAmountEntry['value__sum'] = 0

    DailyValueOutput = Balance.objects.all().filter(
        typeoperation='E', datecreate__day=timezone.now().day).aggregate(Sum('value'))  # noqa
    if DailyValueOutput['value__sum'] is None:
        DailyValueOutput['value__sum'] = 0

    DailyTotal = DailyAmountEntry['value__sum'] -\
        DailyValueOutput['value__sum']

    # calculate the monthly total
    MonthlyValueEntry = Balance.objects.all().filter(
        typeoperation='P', datecreate__month=timezone.now().month).aggregate(Sum('value'))  # noqa
    if MonthlyValueEntry['value__sum'] is None:
        MonthlyValueEntry['value__sum'] = 0
    MonthlyValueOutput = Balance.objects.all().filter(
        typeoperation='E', datecreate__month=timezone.now().month).aggregate(Sum('value'))  # noqa
    if MonthlyValueOutput['value__sum'] is None:
        MonthlyValueOutput['value__sum'] = 0

    MonthlyTotal = MonthlyValueEntry['value__sum'] - \
        MonthlyValueOutput['value__sum']

    # calculate the annual total
    YearlyValueEntry = Balance.objects.all().filter(
        typeoperation='P', datecreate__year=timezone.now().year).aggregate(Sum('value'))  # noqa
    if YearlyValueEntry['value__sum'] is None:
        YearlyValueEntry['value__sum'] = 0

    YearlyValueOutput = Balance.objects.all().filter(
        typeoperation='E', datecreate__year=timezone.now().year).aggregate(Sum('value'))  # noqa
    if YearlyValueOutput['value__sum'] is None:
        YearlyValueOutput['value__sum'] = 0

    YearlyTotal = YearlyValueEntry['value__sum'] - \
        YearlyValueOutput['value__sum']

    context = {
        'datebalances': page_obj,
        'pagination_range': pagination_range,
        'DailyTotal': DailyTotal,
        'MonthlyTotal': MonthlyTotal,
        'YearlyTotal': YearlyTotal,


    }

    return render(request, template_name, context)


@login_required(login_url='accounts:loginUser', redirect_field_name='next')
def createfinance(request):
    if not request.POST:
        raise Http404()
    if request.method == 'POST':
        value = request.POST.get('value')
        typeoperation = request.POST.get('typeoperation')
        user = request.user
        Balance.objects.create(
            value=value, typeoperation=typeoperation, user=user)
        messages.success(request, 'Data saved successfully!')
        return redirect('balancecontrol:home')
    else:
        messages.error(request, 'Data not saved!')
        return redirect(reverse('balancecontrol:home'))


@login_required(login_url='accounts:loginUser', redirect_field_name='next')
def editfinance(request):
    if not request.POST:
        raise Http404()

    if request.method == 'POST':
        code = request.POST.get('code')
        value = request.POST.get('value')
        typeoperation = request.POST.get('typeoperation')
        balance = get_object_or_404(Balance, user=request.user, code=code)
        balance.value = value
        balance.typeoperation = typeoperation
        balance.save()
        messages.success(request, 'Data edited successfully!')
        return redirect('balancecontrol:home')
    else:
        messages.error(request, 'Data not edited!')
        return redirect(reverse('balancecontrol:home'))


@login_required(login_url='accounts:loginUser', redirect_field_name='next')
def deletefinance(request):
    if not request.POST:
        raise Http404()
    if request.method == 'POST':
        code = request.POST.get('code')
        balance = get_object_or_404(Balance, user=request.user, code=code)
        balance.delete()
        messages.success(request, 'Data deleted successfully!')
        return redirect('balancecontrol:home')
    else:
        messages.error(request, 'Data not deleted!')
        return redirect(reverse('balancecontrol:home'))

balancecontrol/templates/balancecontrol/modal/_createfinance.html
  <div class="d-grid gap-2 col-6 mx-auto mb-3">
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createModal">Create Finance</button>
    <!-- Modal -->
    <div class="modal fade" id="createModal" tabindex="-1" aria-labelledby="createModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="createModalLabel">Save Data</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <form action={% url 'balancecontrol:createfinance' %} method="POST">
            {% csrf_token %}
          <div class="modal-body">
              <div class="form-floating mb-3">
                <input type="number" step="any" class="form-control" id="floatingInput" name="value" placeholder="value" required/>
                <label for="floatingInput">Value</label>
              </div>
              
              <select class="form-select" id="selectValue" name="typeoperation">
                  <option selected value="P">Prohibited</option>
                  <option value="E">Exit</option>
              </select>
              
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
          </form>
        </div>
      </div>
    </div>
</div>

balancecontrol/templates/balancecontrol/modal/_deletefinance.html
<button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#deleteModal{{ datebalance.code }}">Delete</button>

<!-- Modal -->
<div class="modal fade" id="deleteModal{{ datebalance.code }}" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="deleteModalLabel">Delete {{ datebalance.value }}</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form action={% url 'balancecontrol:deletefinance'%} method="POST">
        {% csrf_token %}
        <input type="hidden" name="code" value="{{datebalance.code}}" />
        <div class="modal-body">
          <h2>Are you sure you want to delete {{ datebalance.value }}?</h2>
          <h2>This action cannot be reversed.</h2>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-danger">Delete Data</button>
        </div>
      </form>
    </div>
  </div>
</div>

balancecontrol/templates/balancecontrol/modal/_editfinance.html
<!-- Button trigger modal -->
<button type="button" class="btn btn-outline-warning" data-bs-toggle="modal" data-bs-target="#editModal{{datebalance.code}}">
    Edit
</button>
  
  <!-- Modal -->
<div class="modal fade" id="editModal{{datebalance.code}}" tabindex="-1" aria-labelledby="editModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="editModalLabel">Edit R$ {{datebalance.value}}</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
        <form action={% url 'balancecontrol:editfinance' %} method="POST">
          {% csrf_token %}
          <div class="modal-body">
            <input type="hidden" name="code" value="{{datebalance.code}}">
            <div class="form-floating mb-3">
              <input type="number" step="any" class="form-control" id="floatingInput" name="value" placeholder="Value" value="{{datebalance.value}}">
              <label for="floatingInput">Value</label>
            </div>
            <div class="form-floating">
              <select class="form-select" id="floatingSelect" name="typeoperation">
              {% if datebalance.typeoperation == 'P' %}
                <option value="P" selected>Prohibited</option>
                <option value="E">Exit</option>
              {% else %}
                <option value="P" >Prohibited</option>
                <option value="E" selected>Exit</option>
              {% endif %}
              </select>
              <label for="floatingSelect">Works with selects</label>
            </div>
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Save changes</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>