accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.loginUser, name='loginUser'),
    path('register/', views.register, name='register'),
    path('logout/', views.logoutUser, name='logoutUser'),
    path('reset_password/', views.resetPassword, name='resetPassword'),
    path('reset_password_sent/', views.resetPasswordSent,
         name='resetPasswordSent'),
    path('reset', views.resetPasswordConfirm,
         name='resetPasswordConfirm'),
    path('reset_password_complete/', views.resetPasswordComplete,
         name='resetPasswordComplete'),
    path('invalid/', views.resetPasswordInvalid, name='resetPasswordInvalid'),
    path('expired/', views.resetPasswordExpired, name='resetPasswordExpired')
]

balancecontrol/urls.py
from django.urls import path

from . import views

app_name = 'balancecontrol'
urlpatterns = [
    path('', views.home, name='home'),
    path('createfinance/', views.createfinance, name='createfinance'),
    path('editfinance/', views.editfinance, name='editfinance'),
    path('deletefinance/', views.deletefinance, name='deletefinance'),
]

settings/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('balancecontrol.urls')),
    path('accounts/', include('accounts.urls')),
]

templates/partial/_footer.html
{% load static %}

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"></script>

templates/partial/_head.html
{% load static %}

<!--boostrap-->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">
<!--Icons of boostrap-->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
<link rel="stylesheet" href="{% static 'assets/custom/css/style.css'%}">

templates/partial/_messages.html
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
{% if messages %}
    {% for message in messages %}
        <script>
            swal({
                text: "{{ message }}",
                icon: "{{ message.tags }}",
              });
        </script>
    {% endfor %}
{% endif %}

templates/partial/_nav.html
<nav class="navbar bg-light mb-3">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><img src="https://res.cloudinary.com/deezimjer/image/upload/v1670954867/Balance_control_1_suz1kn.png" alt="Bootstrap" width="60" height="60" /></a>
    <a href={% url 'balancecontrol:home' %} class="navbar-brand text-center"> Balance Control</a>
    <span class="navbar-brand text-center">Welcome {{ user.username }}</span>
    <form action="{% url 'accounts:logoutUser' %}" method="POST" >
      {% csrf_token %}
      <button type="submit" class="btn btn-light">Logout</button>
    </form>
  </div>
</nav>

templates/partial/_pagination.html
{% if datebalances.has_other_pages %}
<nav>
  <ul class="pagination justify-content-center">

  {% if pagination_range.first_page_out_of_range %}
    <a class="page-link page-item" href="?page=1">1</a>
    <span class="page-link page-item">...</span>
  {% endif %}
  {% for page in pagination_range.pagination %}
    <a class="page-link page-item" href="?page={{ page }}">{{ page }}</a>
  {% endfor %}
  {% if pagination_range.last_page_out_of_range %}
        <span class="page-link page-item">...</span>
        <a class="page-link page-item" href="?page={{ pagination_range.total_pages }}">{{ pagination_range.total_pages }}</a>
  {% endif %}    

  </ul>
</nav>
{% endif %}

templates/partial/messages.html
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
{% if messages %}
    {% for message in messages %}
        <script>
            swal({
                text: "{{ message }}",
                icon: "{{ message.tags }}",
              });
        </script>
    {% endfor %}
{% endif %}